version: '3.5'
services:
  discount-service:
    build: ""
    environment:
      - ENVIRONMENT=local
    ports:
      - "8080:8080"
      - "5006:5006"
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
